### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by OffifialMITX** [lmweav/SchoolQuest#2]
Could you please submit your app to [F-Droid](f-droid.org)? I've checked around a little with my practically non-existent programming knowlege, and it doesn't seem like your app depends on Google much (which is their basically only standard, besides from everything having to be Open Source), and I'd love it being a part of it.

I can't help out much myself, other than pointing to [their help page](https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included), sorry.

_Sent from my Moto E (4) Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by lmweav** [comment]
Hi, unfortunately I can't submit it to F-droid, as it would mean making all my assets open-source. However, you can download an apk from the releases page! Hopefully you'll be able to install it from there!

**Comment by OffifialMITX** [comment]
Which assets are not Open Source?

**Comment by lmweav** [comment]
I haven't made most of the image, text and xml resources open-source. I provided a few samples here to help people who wish to use the engine, but I didn't upload the rest.

**Comment by OffifialMITX** [comment]
Well, I don't know about the text and xml, but if it helps, I'd be willing to re-make the image ressources, in case you're interested in having a fully Open Source version of this project.

**Comment by lmweav** [comment]
I haven't made the project fully open-source as I want the engine behind the game to be open source, rather than the game itself. All the code is accessible, but to prevent people straight-up copying the game I withheld most of the resources.
